timezone: UTC
adsbx:
  # URL for ADSB Exchange. Not required unless you have
  # a local cache of the API
  # url: http://proxy.localhost:8080/api/aircraft/json/
  apikey: ADSBX API KEY
beast:
  # Configure a single local beast server (dump1090 or readsb)
  - name: home
    host: localhost
    port: 30005
airports:
  # Directories containing OpenAIP files for airport geocoding.
  # Register an account on openaip.net to download the files you need.
  openaip:
    - ./openaip-gb/
    - ./openaip-de/
  cup:
    - ./cup-us/
    - ./cup-ru/
email:
  # Notifications driver. Currently only smtp is supported
  driver: "smtp"
  smtp:
    # Sender email address
    sender: sender@domain.local
    # SMTP username
    username: sender@domain.local
    # SMTP password
    password: YOUR PASSWORD
    # The SMTP server's hostname/ip
    host: SMTP HOST
    # The SMTP server port
    port: SMTP PORT
    # whether to connect using TLS (port 587)
    tls: false
    # if set to true, connections to servers which do not
    # advertise STARTTLS support will cause an error.
    mandatory_starttls: true
    # disables opportunistic encryption of connection with STARTTLS
    # if this is set to true
    nostarttls: false
database:
  # Database driver. Currently supports 'mysql' and 'sqlite3'
  driver: mysql
  # DB Host - server to connect to if using mysql
  host: server.local
  # DB Port - server port if using mysql
  port: 3306
  # DB Username - username for mysql connection
  username: airtrack
  # DB Password - password for mysql connection
  password: password
  # Selected Database
  # if driver is mysql, this is the database on the mysql server
  # if driver is sqlite3, this is the filesystem path to the DB
  database: airtrack
sighting:
  # close sightings if no messages have been received in this long
  # unit: seconds
  timeout: 60
  # The number of messages with the same value required to change on_ground status
  onground_update_threshold: 6
# Prometheus metrics configuration (pull based)
metrics:
  # Whether to enable prometheus metrics
  enabled: false
  # Exposed HTTP metrics on this port
  port: 9206
# Configuration for map HTTP server. This section
# matches the defaults
map:
  # Interface the HTTP server will listen on
  interface: 0.0.0.0
  # Port for the HTTP server. Default is 8080
  port: 8080
  # Disable map server. Default is false.
  disabled: false
  # Number of seconds before creating a new history file. Default
  # is every 30 seconds.
  history_interval: 30
  # Number of history files to maintain. Default is to
  # store 60 files. Defaults should store 30 minutes of history files.
  history_count: 60
  # The map layouts to provide. Essentially different map skins.
  services:
    - dump1090
    - tar1090
projects:
  # Sample project configuration
  - name: German aircraft
    # Set a filter for this project. Can be omitted if not required.
    filter: state.CountryCode == "DE"
    # Whether to reopen a sighting if it was closed recently, due
    # to bad coverage, etc
    reopen_sightings: true
    # Project specific notification configuration
    notifications:
      # Destination for notifications
      email: mymail@domain.local
      # List of enabled email notifications
      events:
        - map_produced
        - spotted_in_flight
        - takeoff_start
        - takeoff_complete
    # List of features enabled for the project
    features:
      - track_tx_types
      - track_callsigns
      - track_squawks
      - track_kml
      - track_takeoff
      - geocode_endpoints
